import React,{useEffect,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import ReactMarkdown from"react-markdown";
import type{Attachment,Conversation,Message,UserProfile,ApprovalMode}from"@ade/shared";
import"./style.css";
type BrowserQueueItem={id:string;objective:string;title?:string;url?:string;created?:number};
const base=(import.meta as ImportMeta&{env:Record<string,string>}).env.VITE_API_URL??"http://127.0.0.1:4000";
const token=()=>sessionStorage.getItem("ade_access");
let refreshInFlight:Promise<boolean>|undefined;
/** Usa il cookie ade_refresh (30 giorni) per ottenere silenziosamente un nuovo access token (15 minuti),
 * senza far ripassare l'utente dal login Google. Ritorna false solo se il cookie non è più valido. */
async function silentRefresh():Promise<boolean>{
  if(!refreshInFlight)refreshInFlight=(async()=>{
    try{const r=await fetch(base+"/v1/auth/refresh",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:"{}"});if(!r.ok)return false;const data=await r.json();if(!data.accessToken)return false;sessionStorage.setItem("ade_access",data.accessToken);return true}
    catch{return false}
    finally{refreshInFlight=undefined}
  })();
  return refreshInFlight;
}
async function api(path:string,init?:RequestInit,retried=false):Promise<any>{const multipart=init?.body instanceof FormData;const r=await fetch(base+path,{credentials:"include",...init,headers:{...(multipart?{}:{"Content-Type":"application/json"}),...(token()?{Authorization:`Bearer ${token()}`}:{ }),...init?.headers}});if(r.status===401){if(!retried&&path!=="/v1/auth/refresh"&&await silentRefresh())return api(path,init,true);throw new Error("Accedi per continuare")}if(!r.ok){const detail=await r.json().catch(()=>({}));throw new Error(detail.error??detail.detail??"Errore server")}return r.json()}
function App(){
 const[profile,setProfile]=useState<UserProfile>();const[conversations,setConversations]=useState<Conversation[]>([]);const[active,setActive]=useState<string>();const[messages,setMessages]=useState<Message[]>([]);const[text,setText]=useState("");const[error,setError]=useState("");const[dark,setDark]=useState(true);const[busy,setBusy]=useState(false);const[authBusy,setAuthBusy]=useState(false);const[telegramCode,setTelegramCode]=useState("");const[files,setFiles]=useState<Attachment[]>([]);const[query,setQuery]=useState("");const[sidebar,setSidebar]=useState(true);const fileInput=useRef<HTMLInputElement>(null);const end=useRef<HTMLDivElement>(null);const authenticated=Boolean(token()&&profile);
 const[showConnectors,setShowConnectors]=useState(false);const[workspace,setWorkspace]=useState<{connected:boolean;scopes:string[]}>();const[approvals,setApprovals]=useState<Array<{id:string;action:string;data_summary:string;risk:string;created_at:string}>>([]);const[connectBusy,setConnectBusy]=useState(false);const[decidingId,setDecidingId]=useState<string>();const[showPlusMenu,setShowPlusMenu]=useState(false);
 const[showSettings,setShowSettings]=useState(false);const[settingsBusy,setSettingsBusy]=useState<string>();const[showApprovalMenu,setShowApprovalMenu]=useState(false);
 const approvalOptions:Array<[ApprovalMode,string,string,boolean]>=[["strict","Richiedi approvazione","Chiedi sempre prima di ogni azione esterna: calendario, Drive, email, immagini, documenti, PC, browser.",false],["balanced","Approva per me","Chiedi l'approvazione solo per azioni potenzialmente rischiose (email, PC, azioni poco chiare); il resto parte subito, come per un'azione di routine.",false],["full","Accesso completo","Nessuna conferma, nemmeno per inviare email o controllare il PC. Usa solo se ti fidi completamente di ADE.",true]];
 const approvalModeMeta:Record<ApprovalMode,{icon:string;label:string}>={strict:{icon:"🤚",label:"Richiedi approvazione"},balanced:{icon:"🤝",label:"Approva per me"},full:{icon:"🔓",label:"Accesso completo"}};
 const[browserQueue,setBrowserQueue]=useState<BrowserQueueItem[]>([]);const[queueBusyId,setQueueBusyId]=useState<string>();
 const[podStatus,setPodStatus]=useState<{configured:boolean;running:boolean;idleMinutes?:number}>();const[waking,setWaking]=useState(false);const[wakeError,setWakeError]=useState("");
 const[notifyEnabled,setNotifyEnabled]=useState(()=>typeof Notification!=="undefined"&&Notification.permission==="granted");const notifyRef=useRef(notifyEnabled);useEffect(()=>{notifyRef.current=notifyEnabled},[notifyEnabled]);
 const prevPodRunning=useRef<boolean|undefined>(undefined);const[podJustReady,setPodJustReady]=useState(false);
 function toggleNotify(){if(typeof Notification==="undefined"){setWakeError("Il browser non supporta le notifiche desktop.");return}if(Notification.permission==="denied"){setWakeError("Le notifiche sono bloccate: abilitale dalle impostazioni del sito nel browser.");return}if(Notification.permission==="granted"){setNotifyEnabled(v=>!v);return}void Notification.requestPermission().then(p=>{setNotifyEnabled(p==="granted");if(p!=="granted")setWakeError("Permesso notifiche non concesso.")})}
 async function loadPodStatus(){try{const s=await api("/v1/system/pod-status");if(prevPodRunning.current===false&&s.running){setPodJustReady(true);setTimeout(()=>setPodJustReady(false),10000);if(notifyRef.current&&typeof Notification!=="undefined")new Notification("ADE è pronto",{body:"Il pod si è riavviato: puoi continuare a lavorare.",icon:"/favicon.svg"})}prevPodRunning.current=s.running;setPodStatus(s)}catch{ }}
 async function wakePod(){setWaking(true);setWakeError("");try{await api("/v1/system/wake",{method:"POST",body:"{}"});const status=await api("/v1/system/pod-status");setPodStatus(status);if(!status.running)setWakeError("Il pod non risulta ancora attivo: potrebbe metterci un minuto, oppure controlla lo stato su console.runpod.io.")}catch(e){setWakeError((e as Error).message.startsWith("runpod_start_failed")?"RunPod non è riuscito ad avviare il pod (errore della piattaforma). Controlla stato e credito su console.runpod.io.":(e as Error).message)}finally{setWaking(false)}}
 useEffect(()=>{if(!authenticated)return;void loadPodStatus();const id=setInterval(()=>void loadPodStatus(),30000);return()=>clearInterval(id)},[authenticated]);
 const load=async()=>{const raw:Array<Conversation&{conversation_id?:string;updated_at?:string}>=await api("/v1/conversations");const items=raw.map(item=>({id:item.id??item.conversation_id??"",title:item.title??item.conversation_id??"Nuova conversazione",updatedAt:item.updatedAt??item.updated_at??""}));setConversations(items);setActive(current=>current??items[0]?.id)};
 useEffect(()=>{void(async()=>{try{if(!token()){let refreshToken:string|undefined;if("__TAURI_INTERNALS__"in window){const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a:Record<string,string>)=>Promise<string|undefined>}}).__TAURI_INTERNALS__.invoke;refreshToken=await invoke("secret_read",{name:"refresh_token"})}const r=await api("/v1/auth/refresh",{method:"POST",body:JSON.stringify({refreshToken})});sessionStorage.setItem("ade_access",r.accessToken);if(refreshToken&&r.refreshToken&&"__TAURI_INTERNALS__"in window){const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a:Record<string,string>)=>Promise<void>}}).__TAURI_INTERNALS__.invoke;await invoke("secret_store",{name:"refresh_token",value:r.refreshToken})}}setProfile(await api("/v1/me"));await load()}catch{sessionStorage.removeItem("ade_access")}})()},[]);
 async function loadMessages(convId:string){const items:Array<Message&{text?:string}>=await api(`/v1/conversations/${convId}/messages`);return items.map((item,index)=>({...item,id:item.id??`${convId}-${index}`,conversationId:item.conversationId??convId,content:item.content??item.text??"",attachments:item.attachments??[],channel:item.channel??"desktop",createdAt:item.createdAt??""}))}
 useEffect(()=>{if(active)void loadMessages(active).then(setMessages).catch(e=>setError(e.message))},[active]);
 // I task compositi (complex_task) finiscono in background e consegnano il risultato come nuovo messaggio
 // asincrono (vedi complex-task-runtime.ts sul server): senza un refresh periodico l'utente non lo
 // vedrebbe finché non riapre/cambia conversazione. Confronto la lunghezza prima di aggiornare lo stato
 // per non causare re-render/flicker inutili quando non c'è nulla di nuovo.
 useEffect(()=>{if(!active)return;const id=setInterval(()=>{void loadMessages(active).then(items=>setMessages(prev=>items.length!==prev.length?items:prev)).catch(()=>{})},6000);return()=>clearInterval(id)},[active]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth"})},[messages,busy]);
 async function login(){setAuthBusy(true);setError("");try{if("__TAURI_INTERNALS__"in window){const start=await api("/v1/auth/desktop/start",{method:"POST",body:"{}"});const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a:Record<string,string>)=>Promise<void>}}).__TAURI_INTERNALS__.invoke;await invoke("open_external",{url:start.url});for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,2000));const response=await fetch(`${base}/v1/auth/desktop/status/${encodeURIComponent(start.requestId)}`);if(response.status===410)throw new Error("Accesso scaduto: riprova");const result=await response.json();if(result.status==="complete"){sessionStorage.setItem("ade_access",result.accessToken);await invoke("secret_store",{name:"refresh_token",value:result.refreshToken});setProfile(await api("/v1/me"));await load();return}}throw new Error("Tempo di accesso scaduto")}location.assign(`${base}/v1/auth/google/start`)}catch(e){setError((e as Error).message)}finally{setAuthBusy(false)}}
 async function create(){if(!token())return void login();const c=await api("/v1/conversations",{method:"POST",body:"{}"});setActive(c.id);setMessages([]);setFiles([]);await load()}
 async function upload(list:FileList|null){if(!list)return;if(!token())return void login();setBusy(true);try{const added:Attachment[]=[];for(const file of Array.from(list).slice(0,10)){const form=new FormData();form.append("file",file);added.push(await api("/v1/attachments",{method:"POST",body:form}))}setFiles(old=>[...old,...added])}catch(e){setError((e as Error).message)}finally{setBusy(false);if(fileInput.current)fileInput.current.value=""}}
 async function send(){if(!token())return void login();if(!text.trim()||!active)return;const content=text;setText("");setBusy(true);try{await api(`/v1/conversations/${active}/messages`,{method:"POST",body:JSON.stringify({content,channel:"__TAURI_INTERNALS__"in window?"desktop":"web",attachmentIds:files.map(f=>f.id)})});setFiles([]);setMessages(await api(`/v1/conversations/${active}/messages`));await load();setError("")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function linkTelegram(){if(!token())return void login();setTelegramCode((await api("/v1/telegram/link-code",{method:"POST",body:"{}"})).code)}async function revokeTelegram(){await api("/v1/telegram/link",{method:"DELETE"});setTelegramCode("")}
 async function loadBrowserQueue(){if(!("__TAURI_INTERNALS__"in window))return;try{const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a?:Record<string,unknown>)=>Promise<BrowserQueueItem[]>}}).__TAURI_INTERNALS__.invoke;setBrowserQueue(await invoke("browser_queue_list"))}catch{ }}
 async function loadConnectors(){try{setWorkspace(await api("/v1/google/workspace/status"));setApprovals(await api("/v1/approvals"));await loadBrowserQueue()}catch(e){setError((e as Error).message)}}
 async function openConnectors(){if(!authenticated)return void login();setShowPlusMenu(false);setShowConnectors(true);await loadConnectors()}
 function openSettings(){if(!authenticated)return void login();setShowSettings(true)}
 async function updateSettings(patch:Partial<Pick<UserProfile,"approvalMode"|"computerUseEnabled"|"browserUseEnabled">>){setSettingsBusy(Object.keys(patch)[0]);try{const updated=await api("/v1/settings",{method:"PUT",body:JSON.stringify(patch)});setProfile(p=>p?{...p,...updated}:p)}catch(e){setError((e as Error).message)}finally{setSettingsBusy(undefined)}}
 async function dismissBrowserRequest(id:string){const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a?:Record<string,unknown>)=>Promise<void>}}).__TAURI_INTERNALS__.invoke;await invoke("browser_queue_dismiss",{id});setBrowserQueue(items=>items.filter(x=>x.id!==id))}
 async function sendBrowserRequest(item:BrowserQueueItem){setQueueBusyId(item.id);try{let conversationId=active;if(!conversationId){const c=await api("/v1/conversations",{method:"POST",body:"{}"});conversationId=c.id;await load()}await api(`/v1/conversations/${conversationId}/messages`,{method:"POST",body:JSON.stringify({content:`/naviga ${item.objective}`,channel:"desktop"})});setActive(conversationId);setMessages(await api(`/v1/conversations/${conversationId}/messages`));await dismissBrowserRequest(item.id)}catch(e){setError((e as Error).message)}finally{setQueueBusyId(undefined)}}
 async function rejectBrowserRequest(id:string){setQueueBusyId(id);try{await dismissBrowserRequest(id)}catch(e){setError((e as Error).message)}finally{setQueueBusyId(undefined)}}
 async function connectGoogle(){setConnectBusy(true);try{const start=await api("/v1/google/workspace/start",{method:"POST",body:"{}"});if("__TAURI_INTERNALS__"in window){const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a:Record<string,string>)=>Promise<void>}}).__TAURI_INTERNALS__.invoke;await invoke("open_external",{url:start.url})}else location.assign(start.url)}catch(e){setError((e as Error).message)}finally{setConnectBusy(false)}}
 async function disconnectGoogle(){try{await api("/v1/google/workspace",{method:"DELETE"});await loadConnectors()}catch(e){setError((e as Error).message)}}
 async function decideApproval(id:string,approved:boolean){setDecidingId(id);try{await api(`/v1/approvals/${id}/decision`,{method:"POST",body:JSON.stringify({approved})});await loadConnectors();if(active)setMessages(await api(`/v1/conversations/${active}/messages`))}catch(e){setError((e as Error).message)}finally{setDecidingId(undefined)}}
 async function logout(){let refreshToken:string|undefined;if("__TAURI_INTERNALS__"in window){const invoke=(window as unknown as{__TAURI_INTERNALS__:{invoke:(c:string,a:Record<string,string>)=>Promise<string|undefined>}}).__TAURI_INTERNALS__.invoke;refreshToken=await invoke("secret_read",{name:"refresh_token"});await invoke("secret_delete",{name:"refresh_token"})}await api("/v1/auth/logout",{method:"POST",body:JSON.stringify({refreshToken})});sessionStorage.removeItem("ade_access");setProfile(undefined);setConversations([]);setMessages([]);setActive(undefined)}
 const visible=conversations.filter(c=>(c.title||"").toLowerCase().includes(query.toLowerCase()));return <main className={`${dark?"dark":"light"} ${sidebar?"":"sidebar-closed"}`}>
 <aside><div className="brand"><span className="brand-mark">A</span><h1>ADE</h1><button className="icon-button" onClick={()=>setSidebar(false)}>‹</button></div><button className="new-chat" onClick={()=>void create()}><span>＋</span> Nuova chat</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca nelle chat"/><nav>{visible.map(c=><button className={active===c.id?"active":""} onClick={()=>setActive(c.id)} key={c.id}>{c.title||"Nuova conversazione"}</button>)}</nav><footer><button onClick={()=>void openConnectors()}>◫ Connettori e plugin{approvals.length>0?` (${approvals.length})`:""}</button><button onClick={()=>openSettings()}>⚙ Impostazioni</button><button onClick={()=>void linkTelegram()}>Telegram</button>{telegramCode&&<div className="telegram-card"><small>Codice monouso</small><output>{telegramCode}</output><button onClick={()=>void revokeTelegram()}>Revoca</button></div>}{podStatus?.configured&&<div className="pod-status"><div style={{display:"flex",alignItems:"center",gap:7,width:"100%"}}><span className={`pod-dot ${podStatus.running?"on":"off"}${waking?" waking":""}`}/><small>{waking?"Risveglio del pod in corso…":podStatus.running?"ADE attivo":`ADE in pausa${podStatus.idleMinutes?` (si spegne dopo ${podStatus.idleMinutes} min di inattività)`:""}`}</small><button className="icon-button" title={notifyEnabled?"Notifiche attive: ti avviso quando ADE è pronto":"Attiva le notifiche per essere avvisata quando ADE è pronto"} onClick={toggleNotify}>{notifyEnabled?"🔔":"🔕"}</button>{!podStatus.running&&<button onClick={()=>void wakePod()} disabled={waking}>{waking?"Riaccensione…":"Riaccendi"}</button>}</div>{podJustReady&&<small style={{display:"block",marginTop:4,color:"#4ade80"}}>✅ ADE è pronto</small>}{wakeError&&<small className="auth-error" style={{display:"block",marginTop:4}}>{wakeError}</small>}</div>}<div className="profile-row"><span className="avatar">{profile?.name?.slice(0,1)||"A"}</span><span>{profile?.name||"Account ADE"}</span><button className="icon-button" onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button>{authenticated&&<button className="icon-button" onClick={()=>void logout()}>↪</button>}</div></footer></aside>
 <section className="chat-panel"><header>{!sidebar&&<button className="icon-button" onClick={()=>setSidebar(true)}>☰</button>}<div><strong>ADE</strong><small>Assistente orchestratore</small></div>{authenticated?<span className={`status ${error?"offline":""}`}><i/> {error||"RunPod connesso"}</span>:<button className="google-login" onClick={()=>void login()} disabled={authBusy}>{authBusy?"In attesa di Google…":"Accedi con Google"}</button>}</header><article>{!active&&<div className="welcome"><span className="brand-mark large">A</span><h2>Come posso aiutarti?</h2><p>{authenticated?"Scrivi una richiesta, allega un file oppure continua una conversazione iniziata da Telegram.":"L’interfaccia completa è pronta. Accedi con Google per sincronizzare cronologia, allegati, plugin, Chrome e Telegram."}</p><button onClick={()=>void create()}>{authenticated?"Inizia una nuova chat":"Accedi e inizia"}</button>{error&&<p className="auth-error">{error}</p>}</div>}{messages.map(m=><div className={`message-row ${m.role}`} key={m.id}><div className="message"><ReactMarkdown>{m.content}</ReactMarkdown></div></div>)}{busy&&<div className="message-row assistant"><div className="message typing">{podStatus?.configured&&!podStatus.running?<span>ADE si sta svegliando, può richiedere qualche minuto…</span>:<><i/><i/><i/></>}</div></div>}<div ref={end}/></article>
 {files.length>0&&<div className="attachment-tray">{files.map(f=><span key={f.id}>{f.name}<button onClick={()=>setFiles(items=>items.filter(x=>x.id!==f.id))}>×</button></span>)}</div>}<div className="composer-wrap"><div className="composer"><input ref={fileInput} type="file" multiple hidden onChange={e=>{void upload(e.target.files);setShowPlusMenu(false)}}/><div className="plus-wrap">{showPlusMenu&&<div className="plus-menu-backdrop" onClick={()=>setShowPlusMenu(false)}/>}<button className="attach" title="Plugin e allegati" onClick={()=>{if(!authenticated)return void login();if(!showPlusMenu)void api("/v1/google/workspace/status").then(setWorkspace).catch(()=>{});setShowPlusMenu(v=>!v)}}>＋</button>{showPlusMenu&&<div className="plus-menu">
 <div className="plus-menu-section">Plugin</div>
 <button onClick={()=>{setShowPlusMenu(false);void(workspace?.connected?openConnectors():connectGoogle())}}><span className="plus-menu-icon">📧</span><span><strong>Gmail</strong><small>{workspace?.connected?"Connesso":"Leggere e inviare email"}</small></span>{workspace?.connected&&<span className="plugin-check">✓</span>}</button>
 <button onClick={()=>{setShowPlusMenu(false);void(workspace?.connected?openConnectors():connectGoogle())}}><span className="plus-menu-icon">📅</span><span><strong>Google Calendar</strong><small>{workspace?.connected?"Connesso":"Gestire eventi e agenda"}</small></span>{workspace?.connected&&<span className="plugin-check">✓</span>}</button>
 <button onClick={()=>{setShowPlusMenu(false);void(workspace?.connected?openConnectors():connectGoogle())}}><span className="plus-menu-icon">📁</span><span><strong>Google Drive</strong><small>{workspace?.connected?"Connesso":"Salvare e cercare file"}</small></span>{workspace?.connected&&<span className="plugin-check">✓</span>}</button>
 <button onClick={()=>setShowPlusMenu(false)}><span className="plus-menu-icon">📄</span><span><strong>Documenti, PDF, fogli</strong><small>Sempre disponibile, nessuna connessione richiesta</small></span><span className="plugin-check">✓</span></button>
 <div className="plus-menu-row"><span className="plus-menu-icon">🌐</span><span><strong>Browser</strong><small>{(profile?.browserUseEnabled??true)?"Attivo":"Disattivato"}</small></span><label className="switch"><input type="checkbox" checked={profile?.browserUseEnabled??true} onChange={e=>void updateSettings({browserUseEnabled:e.target.checked})}/><span/></label></div>
 <div className="plus-menu-row"><span className="plus-menu-icon">🖥️</span><span><strong>Controllo del PC</strong><small>{(profile?.computerUseEnabled??true)?"Attivo":"Disattivato"}</small></span><label className="switch"><input type="checkbox" checked={profile?.computerUseEnabled??true} onChange={e=>void updateSettings({computerUseEnabled:e.target.checked})}/><span/></label></div>
 <button onClick={()=>{setShowPlusMenu(false);fileInput.current?.click()}}><span className="plus-menu-icon">📎</span><span><strong>Allega file o foto</strong><small>Immagini, PDF, documenti</small></span></button>
 <button onClick={()=>{setShowPlusMenu(false);openSettings()}}><span className="plus-menu-icon">⚙</span><span><strong>Tutte le impostazioni</strong><small>Approvazioni, connettori, PC, browser</small></span></button>
 </div>}</div><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={authenticated?(active?"Invia un messaggio ad ADE":"Crea una chat per iniziare"):"Accedi con Google per scrivere ad ADE"} disabled={!authenticated||!active}/><button className="send" onClick={()=>void send()} disabled={!active||busy||!text.trim()}>↑</button></div><div className="approval-pill-row"><div className="approval-pill-wrap">{showApprovalMenu&&<div className="plus-menu-backdrop" onClick={()=>setShowApprovalMenu(false)}/>}<button className="approval-pill" onClick={()=>authenticated?setShowApprovalMenu(v=>!v):void login()}><span>{approvalModeMeta[profile?.approvalMode??"balanced"].icon}</span>{approvalModeMeta[profile?.approvalMode??"balanced"].label}</button>{showApprovalMenu&&<div className="approval-popup"><div className="approval-level">{approvalOptions.map(([mode,label,desc,warn])=>{const current=profile?.approvalMode??"balanced";return <div key={mode} className={`approval-option${warn?" warn":""}${current===mode?" selected":""}`} onClick={()=>{void updateSettings({approvalMode:mode});setShowApprovalMenu(false)}}><div><strong>{label}</strong><small>{desc}</small></div><span className="check">{current===mode?"✓":""}</span></div>})}</div></div>}</div></div><small>ADE può commettere errori. Verifica le informazioni importanti e approva sempre le azioni esterne.</small></div></section>
 {showConnectors&&<div className="modal-backdrop" onClick={()=>setShowConnectors(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowConnectors(false)}>✕</button><h3>Connettori e plugin</h3><small style={{color:"var(--muted)"}}>Collega servizi esterni e gestisci le azioni che ADE ti propone.</small>
 <h4>Google Workspace</h4>{workspace?.connected?<div className="connector-row"><div><strong>Google collegato</strong><small>Calendario, Drive, Gmail</small></div><button onClick={()=>void disconnectGoogle()}>Scollega</button></div>:<div className="connector-row"><div><strong>Google Workspace</strong><small>Calendario, Drive, Gmail</small></div><button className="primary" onClick={()=>void connectGoogle()} disabled={connectBusy}>{connectBusy?"Attendi…":"Collega"}</button></div>}
 <h4>Approvazioni in attesa</h4>{approvals.length===0&&<p className="empty-hint">Nessuna azione in attesa. Quando chiedi ad ADE di fare qualcosa (browser, calendario, Drive, email) comparirà qui prima di essere eseguita.</p>}{approvals.map(a=><div className="approval-card" key={a.id}><strong>{a.action}</strong><span className={`risk ${a.risk}`}>{a.risk}</span><p>{a.data_summary}</p><div className="approval-actions"><button className="approve" disabled={decidingId===a.id} onClick={()=>void decideApproval(a.id,true)}>Approva</button><button className="reject" disabled={decidingId===a.id} onClick={()=>void decideApproval(a.id,false)}>Rifiuta</button></div></div>)}
 {"__TAURI_INTERNALS__"in window&&<><h4>Richieste dal browser</h4>{browserQueue.length===0&&<p className="empty-hint">Nessuna richiesta in attesa. Usa il popup dell'estensione ADE su una scheda di Chrome per inviare una richiesta da rivedere qui.</p>}{browserQueue.map(item=><div className="approval-card" key={item.id}><strong>{item.objective}</strong>{(item.title||item.url)&&<p>{item.title}{item.title&&item.url?" — ":""}{item.url}</p>}<div className="approval-actions"><button className="approve" disabled={queueBusyId===item.id} onClick={()=>void sendBrowserRequest(item)}>Invia ad ADE</button><button className="reject" disabled={queueBusyId===item.id} onClick={()=>void rejectBrowserRequest(item.id)}>Rifiuta</button></div></div>)}</>}
 </div></div>}
 {showSettings&&<div className="modal-backdrop" onClick={()=>setShowSettings(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowSettings(false)}>✕</button><h3>Impostazioni</h3><small style={{color:"var(--muted)"}}>Scegli come ADE gestisce le azioni esterne e cosa può fare sul tuo computer.</small>
 <h4>Come approvare le azioni</h4><div className="approval-level">{approvalOptions.map(([mode,label,desc,warn])=>{const current=profile?.approvalMode??"balanced";return <div key={mode} className={`approval-option${warn?" warn":""}${current===mode?" selected":""}`} onClick={()=>void updateSettings({approvalMode:mode})}><div><strong>{label}</strong><small>{desc}</small></div><span className="check">{settingsBusy==="approvalMode"?"…":current===mode?"✓":""}</span></div>})}</div>
 <h4>Utilizzo del computer</h4>
 <div className="connector-row"><div><strong>Browser</strong><small>Consenti ad ADE di controllare Chrome per compiti multi-step: navigare, cercare, compilare form. {"__TAURI_INTERNALS__"in window?"Richiede l'estensione ADE collegata su Chrome (gestiscila dal popup dell'estensione).":"Disponibile dall'app desktop ADE con l'estensione Chrome collegata."}</small></div><label className="switch"><input type="checkbox" checked={profile?.browserUseEnabled??true} disabled={settingsBusy==="browserUseEnabled"} onChange={e=>void updateSettings({browserUseEnabled:e.target.checked})}/><span/></label></div>
 <div className="connector-row"><div><strong>Controllo del PC</strong><small>Consenti ad ADE di aprire app note e le tue cartelle personali su questo computer.</small></div><label className="switch"><input type="checkbox" checked={profile?.computerUseEnabled??true} disabled={settingsBusy==="computerUseEnabled"} onChange={e=>void updateSettings({computerUseEnabled:e.target.checked})}/><span/></label></div>
 <small style={{display:"block",color:"var(--muted)",margin:"10px 0 6px"}}>App consentite{(profile?.approvalMode??"balanced")==="full"?" — eseguite senza conferma in modalità Accesso completo:":" — richiedono sempre una conferma esplicita:"}</small><div className="allowed-list"><span>Esplora file</span><span>Blocco note</span><span>Calcolatrice</span><span>Gestione attività</span><span>Pannello di controllo</span></div>
 <small style={{display:"block",color:"var(--muted)",margin:"10px 0 6px"}}>Cartelle consentite:</small><div className="allowed-list"><span>Documenti</span><span>Desktop</span><span>Download</span><span>Immagini</span></div>
 </div></div>}
 </main>}
createRoot(document.getElementById("root")!).render(<App/>);
