export const gate2Schema = `
CREATE TABLE IF NOT EXISTS jobs(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL,idempotency_key text NOT NULL,kind text NOT NULL,input jsonb NOT NULL,status text NOT NULL CHECK(status IN ('queued','running','waiting_approval','succeeded','failed','cancelled')),priority int NOT NULL DEFAULT 0,attempt int NOT NULL DEFAULT 0,max_attempts int NOT NULL DEFAULT 3,estimated_cost_cents int NOT NULL DEFAULT 0,actual_cost_cents int NOT NULL DEFAULT 0,available_at timestamptz NOT NULL DEFAULT now(),heartbeat_at timestamptz,locked_by text,last_error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,UNIQUE(user_id,idempotency_key));
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS external_ref text;
CREATE INDEX IF NOT EXISTS jobs_claimable ON jobs(status,available_at,priority DESC,created_at);
CREATE TABLE IF NOT EXISTS job_attempts(id uuid PRIMARY KEY,job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,attempt int NOT NULL,worker_id text NOT NULL,started_at timestamptz NOT NULL DEFAULT now(),heartbeat_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz,outcome text,error_code text,UNIQUE(job_id,attempt));
CREATE TABLE IF NOT EXISTS agent_runs(id uuid PRIMARY KEY,job_id uuid NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,agent text NOT NULL,model text,status text NOT NULL,input_hash text NOT NULL,output jsonb,started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz);
CREATE TABLE IF NOT EXISTS tool_calls(id uuid PRIMARY KEY,agent_run_id uuid NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,tool text NOT NULL,input_hash text NOT NULL,status text NOT NULL,output jsonb,error_code text,started_at timestamptz NOT NULL DEFAULT now(),finished_at timestamptz);
CREATE TABLE IF NOT EXISTS artifacts(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,storage_key text NOT NULL,name text NOT NULL,mime_type text NOT NULL,size bigint NOT NULL,sha256 text NOT NULL,status text NOT NULL,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,sha256,storage_key));
CREATE TABLE IF NOT EXISTS outbox(id uuid PRIMARY KEY,aggregate_type text NOT NULL,aggregate_id uuid NOT NULL,event_type text NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),published_at timestamptz,attempts int NOT NULL DEFAULT 0,last_error text);
CREATE INDEX IF NOT EXISTS outbox_unpublished ON outbox(created_at) WHERE published_at IS NULL;
CREATE TABLE IF NOT EXISTS usage_events(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,job_id uuid REFERENCES jobs(id) ON DELETE SET NULL,provider text NOT NULL,model text NOT NULL,input_tokens int NOT NULL DEFAULT 0,output_tokens int NOT NULL DEFAULT 0,cost_cents int NOT NULL DEFAULT 0,latency_ms int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS channels(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,kind text NOT NULL CHECK(kind IN ('desktop','web','telegram','chrome')),external_id_hash text,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(kind,external_id_hash));
CREATE TABLE IF NOT EXISTS memories(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,conversation_id uuid REFERENCES conversations(id) ON DELETE CASCADE,kind text NOT NULL CHECK(kind IN ('summary','preference','semantic')),content text NOT NULL,source_message_id uuid REFERENCES messages(id) ON DELETE SET NULL,expires_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS data_retention(user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,conversation_days int NOT NULL DEFAULT 365 CHECK(conversation_days BETWEEN 1 AND 3650),audit_days int NOT NULL DEFAULT 365 CHECK(audit_days BETWEEN 30 AND 3650),delete_requested_at timestamptz,delete_after timestamptz,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS legacy_migrations(source_sha256 text PRIMARY KEY,source_label text NOT NULL,source_counts jsonb NOT NULL,imported_counts jsonb NOT NULL,completed_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS memories_user_updated ON memories(user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS channels_user_kind ON channels(user_id,kind);
`;
